#!/usr/bin/env python3
"""Regenerate the "Yo" wordmark vector drawables from the bundled Montserrat Bold.

The wordmark is not hand-drawn: its outlines are extracted from the very font file the app ships,
so the letterforms are exactly Montserrat Bold's — the near-circular geometric "o" and splayed "Y"
that make the mark recognisable. Yo's branding guidelines state the typeface ("Font: Montserrat
Bold") and are explicit that the name is mixed case "Yo", never "YO".

Writes:
  app/src/main/res/drawable/ic_yo_notification.xml   24dp notification small icon
  app/src/main/res/drawable/ic_launcher_monochrome.xml  108dp Android 13 themed-icon layer

Requires fontTools:  python3 -m pip install fonttools
Usage:  python3 tools/generate-yo-vectors.py
"""
from __future__ import annotations

import os
import sys

try:
    from fontTools.misc.transform import Transform
    from fontTools.pens.boundsPen import BoundsPen
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.pens.transformPen import TransformPen
    from fontTools.ttLib import TTFont
except ImportError:  # pragma: no cover - tooling guard
    sys.exit("needs fontTools:  python3 -m pip install fonttools")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = os.path.join(REPO, "app/src/main/res/font/montserrat_bold.ttf")
DRAWABLE = os.path.join(REPO, "app/src/main/res/drawable")
WORDMARK = "Yo"


def build_path(font: TTFont, size: float, pad_fraction: float) -> str:
    """Lay the wordmark out on its advance line, then centre it in a size x size viewport."""
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    names = [cmap[ord(c)] for c in WORDMARK]

    placements = []
    pen_x = 0
    for name in names:
        placements.append((name, pen_x))
        pen_x += hmtx[name][0]

    bounds = BoundsPen(glyph_set)
    for name, offset in placements:
        glyph_set[name].draw(TransformPen(bounds, Transform(1, 0, 0, 1, offset, 0)))
    x_min, _, x_max, y_max = bounds.bounds
    ink_w = x_max - x_min
    ink_h = y_max - bounds.bounds[1]

    pad = size * pad_fraction
    available = size - 2 * pad
    scale = min(available / ink_w, available / ink_h)
    dx = pad + (available - ink_w * scale) / 2 - x_min * scale
    # Font space is Y-up, Android vector space is Y-down, hence the negative y scale.
    dy = pad + (available - ink_h * scale) / 2 + y_max * scale

    commands = []
    for name, offset in placements:
        pen = SVGPathPen(glyph_set, ntos=lambda v: f"{v:.2f}")
        glyph_set[name].draw(
            TransformPen(pen, Transform(scale, 0, 0, -scale, dx + offset * scale, dy))
        )
        drawn = pen.getCommands()
        if drawn:
            commands.append(drawn)
    return " ".join(commands)


def write(path: str, body: str) -> None:
    with open(path, "w") as handle:
        handle.write(body)
    print(f"wrote {os.path.relpath(path, REPO)} ({len(body)} bytes)")


def main() -> None:
    font = TTFont(FONT)
    os.makedirs(DRAWABLE, exist_ok=True)

    write(
        os.path.join(DRAWABLE, "ic_yo_notification.xml"),
        f"""<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by tools/generate-yo-vectors.py - do not hand-edit.
  Notification small icon: the "Yo" wordmark, outlines taken from the bundled Montserrat Bold.
  Android tints small icons solid white, so the fill colour here is nominal.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:fillColor="#FFFFFF"
        android:pathData="{build_path(font, 24.0, 0.08)}" />
</vector>
""",
    )

    write(
        os.path.join(DRAWABLE, "ic_launcher_monochrome.xml"),
        f"""<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by tools/generate-yo-vectors.py - do not hand-edit.
  Themed-icon layer (Android 13+). The shipped 2014 icon was a bare purple square with no glyph, but
  a themed icon with no monochrome mark renders as an empty tile, so this uses the wordmark inside
  the adaptive-icon safe area.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#FFFFFF"
        android:pathData="{build_path(font, 108.0, 0.28)}" />
</vector>
""",
    )


if __name__ == "__main__":
    main()
